<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="styles.css">
    <link href="/css/my-style.css" rel="stylesheet">
    <title>Audemic - <?php echo $view->pageTitle; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=0.9">
</head>
<body><br>
<div class="container"><br>
    <div class="viewer">
        <div id="preview-thumbnail"><br>
            <p1><?php
                $id = $_GET['id'];
                echo $id;
                ?>
            </p1>
        </div>
        <?php
        echo '<a href="viewer.php?id='.$id.'"><img src="images/play.png" id="view-book"></a>'

        ?>

    </div>
    <div class="listen-footer"><br>
        <div class="upload-btn">
            <a href="home.php""><img src="images/home.png" id="upload-image">
            <p1>HOME</p1>
            </a>
        </div>
    </div>
</div>
</body>
</html>